// Code generated by MockGen. DO NOT EDIT.
// Source: src/business/domain/menu/menu.go

// Package mock_menu is a generated GoMock package.
package mock_menu

import (
	entity "go-clean/src/business/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInterface) Create(menu entity.Menu) (entity.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", menu)
	ret0, _ := ret[0].(entity.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInterfaceMockRecorder) Create(menu interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInterface)(nil).Create), menu)
}

// Delete mocks base method.
func (m *MockInterface) Delete(param entity.MenuParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInterfaceMockRecorder) Delete(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInterface)(nil).Delete), param)
}

// Get mocks base method.
func (m *MockInterface) Get(param entity.MenuParam) (entity.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", param)
	ret0, _ := ret[0].(entity.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInterfaceMockRecorder) Get(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInterface)(nil).Get), param)
}

// GetAll mocks base method.
func (m *MockInterface) GetAll(param entity.MenuParam) ([]entity.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", param)
	ret0, _ := ret[0].([]entity.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockInterfaceMockRecorder) GetAll(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockInterface)(nil).GetAll), param)
}

// GetListInByID mocks base method.
func (m *MockInterface) GetListInByID(ids []int64) ([]entity.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListInByID", ids)
	ret0, _ := ret[0].([]entity.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListInByID indicates an expected call of GetListInByID.
func (mr *MockInterfaceMockRecorder) GetListInByID(ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListInByID", reflect.TypeOf((*MockInterface)(nil).GetListInByID), ids)
}

// Update mocks base method.
func (m *MockInterface) Update(selectParam entity.MenuParam, updateParam entity.UpdateMenuParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", selectParam, updateParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInterfaceMockRecorder) Update(selectParam, updateParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInterface)(nil).Update), selectParam, updateParam)
}
