name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Prepare Environment
        run: |
          make swag-install
          go mod download
          make swaggo

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_AWS }}
          username: ${{ secrets.USERNAME_AWS }}
          key: ${{ secrets.KEY_AWS }}
          script: |
            cd creativeland-service
            sudo git pull
            sudo docker build -t cl-app .
            sudo docker container create --name go-app -p 8080:8080 cl-app
            sudo docker container start go-app
